### ISSUE TITLE
save intermediate products of the function, and allow inputting them for subsequent runs

### ISSUE THREAD

**Issue by RosaMGini** [IMI-ConcePTION/CountPersonTime#11]
After conversation with Roel, Davide and Svetlana, the following enhancement is suggested:

1) during execution, the function can, as an option, save the intermediate files (e.g. the individual-level persontime)
2) when running the function, you can foresee as an option that the individual-level persontime is inputted directly as an input

**Comment by relbersumcu** [comment]
If this function is added we need to inform users that it is a best practice to only once calulate the persontimes and save them. Then this saved information is used throughout the rest of the script for the event related calculations that need personlevel information of the persontimes. Also I think it may be better to only select the needed subjects from that persontime table that are relevant. This can be done by saving the persontimes in a SQL(lite) database adding indexes.

**Comment by DavideMessinaARS** [comment]
@relbersumcu I'm kind of confused. I've added the option to save an intermediate file (and load it). Do I need a parameter to filter the intermediate file too?

**Comment by DavideMessinaARS** [comment]
Ok. thanks

**Comment by DavideMessinaARS** [comment]
Done and merged in branch [Version13](https://github.com/IMI-ConcePTION/CountPersonTime/tree/Version13) in https://github.com/IMI-ConcePTION/CountPersonTime/pull/13
