### ISSUE TITLE
Agebands argument should be optional

### ISSUE THREAD

**Issue by DavideMessinaARS** [IMI-ConcePTION/CountPersonTime#18]
In version 13.9 running the function without agebands results in:

![image](https://user-images.githubusercontent.com/78373669/166218157-823f4875-8777-4d56-bb86-903328b0ed22.png)

This is caused by the function trying to calculate the age bands without having Birth_date or Age_bands arguments.

The call to the function was:

```r
CountPersonTime(
  Dataset_events = Input_file1, 
  Dataset = Input_file2,
  Person_id = "person_id",
  Start_study_time = "20120101",
  End_study_time = "20191231",
  Start_date = "start_date", 
  End_date = "end_date",
  Strata = c("sex","city"),
  Name_event = "name_event",
  Date_event = "date_event",
  Increment="day",
  Outcomes_nrec =c("outcome1","outcome2"),
  Unit_of_age = "year",
  include_remaning_ages = T,
  Aggregate = F
)
```

**Comment by relbersumcu** [comment]
I changed row 159 and commented out 161.

**Comment by relbersumcu** [comment]
Section on row 121 was closed before the execution of SplitSpellsAgeBands. Setted the else to row 141

**Comment by DavideMessinaARS** [comment]
Now I get this error when I'm trying to load the function in memory:

![image](https://user-images.githubusercontent.com/78373669/166227842-fd3bc8fb-8634-4297-8119-29e8518c2ff7.png)

**Comment by relbersumcu** [comment]
Can you try again after fetching?

**Comment by DavideMessinaARS** [comment]
It works now thanks. I'm closing this issue
